# Generated by Django 2.0.2 on 2018-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('temp', models.FloatField()),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
